### ISSUE TITLE
How to use EXTRA_FEEDS?

### ISSUE THREAD

**Issue by Miroxyz** [aparcar/action-openwrt-sdk#2]
Can you give me an example of how to use EXTRA_FEEDS environmental variable?
I want to add this line `src-git passwall https://github.com/xiaorouji/openwrt-passwall`

**Comment by aparcar** [comment]
See an example here: https://github.com/libremesh/network-profiles/blob/master/.github/workflows/build.yml#L18

**Comment by Miroxyz** [comment]
@aparcar 👍
